// <auto-generated />
namespace epicnetwork.rocks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class pagelet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pagelet));
        
        string IMigrationMetadata.Id
        {
            get { return "201504291703416_pagelet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
